### ISSUE TITLE
为什么shape_返回reference?

### ISSUE THREAD

**Issue by Dawnborn** [luliyucoordinate/mynet#1]
https://github.com/luliyucoordinate/mynet/blob/c641e38dcc24805f349df324af6a64e8d432353c/core/framework/tensor.hpp#L36

这里直接 return shape_ 为什么会是引用呢？是因为之前声明的函数返回类型决定了具体的返回类型吗？

谢谢解答！

**Comment by luliyucoordinate** [comment]
这里有四种情况：
1. copy 出来
2. move 出来
3. reference
4. pointer
为了性能的考虑我们不采用copy，对于move，那么此时shape_的所有权从Tensor对象的内部移出来了，这不符合语义。最后返回pointer还是reference，pointer的话潜在说tensor可能是nullpter，但是显然这里不是。如果这里的成员才用pointer指向vector结构的话，返回pointer合适。所以这里比较好的做法就是通过reference

**Comment by Dawnborn** [comment]
所以说不用指针是为了防止野指针吗？

**Comment by luliyucoordinate** [comment]
不是，看vector的大小，显然这边的shape_不大，所以copy无所谓；如果很大的话，那么可以通过shared_ptr共享一块内存。另外还有代码复杂度的考虑，成员变量用指针比较麻烦，除非内存极为苛刻。而，shape()函数中其实也可以copy，按照上面的说法（当然这里触发不了copy，会存在编译器的RVO）。**主要原因就是返回的成员不是一个指针类型！**，而成员之所以不是指针理由如上。
